# Generated by Django 3.1.1 on 2021-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Raghav', help_text='Enter you name', max_length=25)),
                ('phone', models.CharField(help_text='Enter you mobile number', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('moto', models.TextField()),
            ],
        ),
    ]
